### ISSUE TITLE
Add a node name to Error object on error 

### ISSUE THREAD

**Issue by enobufs** [DeNA/asyncgraph#2]
When on one of nodes run method fails, it emits 'error' event, but the Error object passed in has no information as to which node that error occurred.

As the asyncgraph knows the name of the node registered, it should add `nodeName` property to Error object so that users can tell where the error occurred.

``` js
asyncgraph.on('error', e) {
    console.log('asyncgraph: Error occurred at node %s', e.nodeName);
}
```

**Comment by bengl** [comment]
Interesting. Do long-stack-trace libraries help at all here by tying stacks together?

**Comment by enobufs** [comment]
If we could tell which modules initialization was failed, the problem solved. Then user can always why the module failed the initialization.
